// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#ifndef DJINNI_GENERATED_ENUM_FROM_STRING_HPP
#define DJINNI_GENERATED_ENUM_FROM_STRING_HPP

#include <string>

namespace textsort {

template <typename T> 
T from_string(const std::string&);

}  // namespace textsort
#endif //DJINNI_GENERATED_ENUM_FROM_STRING_HPP
