// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#ifndef DJINNI_GENERATED_ITEM_LIST_HPP
#define DJINNI_GENERATED_ITEM_LIST_HPP

#include <iostream>
#include <string>
#include <utility>
#include <vector>

namespace textsort {

struct ItemList final {
    std::vector<std::string> items;

    ItemList(std::vector<std::string> items_)
    : items(std::move(items_))
    {}

    ItemList(const ItemList& cpy) {
       this->items = cpy.items;
    }

    ItemList() = default;


    ItemList& operator=(const ItemList& cpy) {
       this->items = cpy.items;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(items);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(items);
    }
};

}  // namespace textsort
#endif //DJINNI_GENERATED_ITEM_LIST_HPP
