// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#ifndef DJINNI_GENERATED_SORT_ITEMS_HPP
#define DJINNI_GENERATED_SORT_ITEMS_HPP

#include <memory>

namespace textsort {

class TextboxListener;
enum class sort_order;
struct ItemList;

class SortItems {
public:
    virtual ~SortItems() {}

    /** For the iOS / Android demo */
    virtual void sort(sort_order order, const ItemList & items) = 0;

    static std::shared_ptr<SortItems> create_with_listener(const std::shared_ptr<TextboxListener> & listener);

    /** For the localhost / command-line demo */
    static ItemList run_sort(const ItemList & items);
};

}  // namespace textsort
#endif //DJINNI_GENERATED_SORT_ITEMS_HPP
