// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <functional>

namespace textsort {

enum class sort_order : int {
    ASCENDING,
    DESCENDING,
    RANDOM,
};
std::string to_string(const sort_order& sort_order);
std::ostream &operator<<(std::ostream &os, const sort_order &o);

}  // namespace textsort

namespace std {

template <>
struct hash<::textsort::sort_order> {
    size_t operator()(::textsort::sort_order type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
