// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "sort_order.hpp"  // my header
#include "enum_from_string.hpp"

namespace textsort {

std::string to_string(const sort_order& sort_order) {
    switch (sort_order) {
        case sort_order::ASCENDING: return "ASCENDING";
        case sort_order::DESCENDING: return "DESCENDING";
        case sort_order::RANDOM: return "RANDOM";
    };
};
template <>
sort_order from_string(const std::string& sort_order) {
    if (sort_order == "ASCENDING") return sort_order::ASCENDING;
    else if (sort_order == "DESCENDING") return sort_order::DESCENDING;
    else return sort_order::RANDOM;
};

std::ostream &operator<<(std::ostream &os, const sort_order &o)
{
    switch (o) {
        case sort_order::ASCENDING:  return os << "ASCENDING";
        case sort_order::DESCENDING:  return os << "DESCENDING";
        case sort_order::RANDOM:  return os << "RANDOM";
    }
}

}  // namespace textsort
