// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#ifndef DJINNI_GENERATED_TEXTBOX_LISTENER_HPP
#define DJINNI_GENERATED_TEXTBOX_LISTENER_HPP

namespace textsort {

struct ItemList;

class TextboxListener {
public:
    virtual ~TextboxListener() {}

    virtual void update(const ItemList & items) = 0;
};

}  // namespace textsort
#endif //DJINNI_GENERATED_TEXTBOX_LISTENER_HPP
